Übung2
23:54:05.072: [codesSE2020] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false push --progress --porcelain MyRepro refs/heads/master:master
error: failed to push some refs to 'https://github.com/LukasWitschel/lwitsc2s.git'
To https://github.com/LukasWitschel/lwitsc2s.git
hint: Updates were rejected because the remote contains work that you do
!	refs/heads/master:refs/heads/master	[rejected] (fetch first)
hint: not have locally. This is usually caused by another repository pushing
Done
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.